name: Build images
#on:
#    push:
#        branches:
#        - master

env:
    REGISTRY: ghcr.io
    IMG_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Login to container registry
          uses: docker/login-action@v1.10.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata
          id: meta
          uses: docker/metadata-action@v3.3.0
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMG_NAME}}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2.6.1
          with:
            context: .
            push: true
            tags: ghcr.io/itimed-toolkit/core_image:devel
            labels: ${{ steps.meta.outputs.labels }}
